# Generated by Django 3.1.3 on 2020-11-15 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password')),
            ],
        ),
    ]
